In [100]:
import numpy as np
import matplotlib.pyplot as plt   

In [101]:
# 水泥问题
# f(x) = 0.56 + 2.19*x1 + 1.15*x2 + 0.75*x3 + 0.48*x4

# shape = 13
# x_dim = 4
# x = np.array([
#     [7, 26, 6, 60],
#     [1, 29, 15, 52],
#     [11, 56, 8, 20],
#     [11, 31, 8, 47],
#     [7, 52, 6, 33],
#     [11, 55, 9, 22],
#     [3, 71, 17, 6],
#     [1, 31, 22, 44],
#     [2, 54, 18, 22],
#     [21, 47, 4, 26],
#     [1, 40, 23, 34],
#     [11, 66, 9, 12],
#     [10, 68, 8, 12]
# ])
# x = np.expand_dims(x, axis=2)
# y = np.array([
#     78.5,
#     74.3,
#     104.3,
#     87.6,
#     95.9,
#     109.2,
#     102.7,
#     72.5,
#     93.1,
#     115.9,
#     83.8,
#     113.3,
#     109.4
# ])
# w = np.random.rand(x_dim+1, 1)
# print(x.shape)
# print(x)
# print(y.shape)


In [102]:
# 读物问题
# f(x) = 6.4 + 74.77*x1 + 0.91*x2

shape = 18
x_dim = 2
learning_rate = 1e-6
x = np.array([
   [4, 171.2],
   [4, 174.2],
   [5,204.3],
   [4,218.7],
   [4,219.4],
   [7,240.4],
   [4,273.5],
   [5,294.8],
   [10,330.2],
   [7,333.1],
   [5,366.0],
   [6,350.9],
   [4,357.9],
   [5,359.0],
   [7,371.9],
   [9,435.3],
   [8,523.9],
   [10,604.1]
])
x = np.expand_dims(x, axis=2)
y = np.array([
    450.5,
    507.7,
    613.9,
    563.4,
    501.5,
    781.5,
    541.8,
    611.1,
    1222.1,
    793.2,
    660.8,
    792.7,
    580.8,
    612.7,
    890.8,
    1121.0,
    1094.2,
    1253.0
])
w = np.random.rand(x_dim+1, 1)
print(x.shape)
print(x)
print(y.shape)


(18, 2, 1)
[[[  4. ]
  [171.2]]

 [[  4. ]
  [174.2]]

 [[  5. ]
  [204.3]]

 [[  4. ]
  [218.7]]

 [[  4. ]
  [219.4]]

 [[  7. ]
  [240.4]]

 [[  4. ]
  [273.5]]

 [[  5. ]
  [294.8]]

 [[ 10. ]
  [330.2]]

 [[  7. ]
  [333.1]]

 [[  5. ]
  [366. ]]

 [[  6. ]
  [350.9]]

 [[  4. ]
  [357.9]]

 [[  5. ]
  [359. ]]

 [[  7. ]
  [371.9]]

 [[  9. ]
  [435.3]]

 [[  8. ]
  [523.9]]

 [[ 10. ]
  [604.1]]]
(18,)


In [103]:
class LinearRegression:
    def __init__(self,x,y,w):
        x = np.concatenate((np.ones((x.shape[0], 1, 1)), x), axis=1)
        print(x[0].shape)
        print(w.shape)
        self.input = x
        self.real = y
        self.weight = w
    def predict(self):
        self.pred = np.zeros(self.input.shape[0])
        for i in range(self.input.shape[0]):
            # self.predict[i] = x[i].T*w
            # print((x[i].T.dot(w)).shape)
            self.pred[i] = np.expand_dims(self.input[i].T.dot(w), axis=0)
    def loss_func(self):
        loss_arr = (self.pred-self.real)**2
        return np.sum(loss_arr/self.input.shape[0])
    def gradient_decent(self, lr):
        accumulated_weight = np.zeros(w.shape)
        for i in range(self.input.shape[0]):
            accumulated_weight += (self.pred[i] - self.real[i])*self.input[i]
        accumulated_weight /= self.input.shape[0]
        self.weight -= lr*accumulated_weight
        self.predict()


In [104]:
lg = LinearRegression(x,y,w)
print(lg.weight)
lg.predict()
print(lg.pred)
print(lg.loss_func())
last_loss = lg.loss_func()
# lg.real.shape
print(lg.real.shape)
lg.gradient_decent(learning_rate)
print(lg.loss_func())
print(lg.weight)

(3, 1)
(3, 1)
[[0.64445737]
 [0.21247797]
 [0.13351118]]
[24.35148246 24.75201599 28.98318033 30.69326329 30.78672111 34.22788969
 38.0096757  41.0659417  46.85462714 46.60437565 50.57193738 48.7683966
 49.2780189  49.63735916 51.78460925 60.6741737  72.29078587 83.42333807]
561327.5368470473
(18,)
443072.39622724487
[[0.64516737]
 [0.21722201]
 [0.38411481]]


In [ ]:
# for epoch in range(100000):
while last_loss - lg.loss_func() > 0.01:
    last_loss = lg.loss_func()
    lg.gradient_decent(learning_rate)
    epoch += 1
    # print("epoch {}, loss:{}".format(epoch+1, lg.loss_func()))

In [107]:
print(lg.weight)

[[ 6.43166866]
 [74.76909407]
 [ 0.91125296]]
