In [28]:
import numpy as np
import matplotlib.pyplot as plt   

In [29]:
class LinearRegression:
    def __init__(self,x,y,w):
        x = np.concatenate((np.ones((x.shape[0], 1, 1)), x), axis=1)
        print(x[0].shape)
        print(w.shape)
        self.input = x
        self.real = y
        self.weight = w
    def predict(self):
        self.pred = np.zeros(self.input.shape[0])
        for i in range(self.input.shape[0]):
            # self.predict[i] = x[i].T*w
            # print((x[i].T.dot(w)).shape)
            self.pred[i] = np.expand_dims(self.input[i].T.dot(w), axis=0)
    def loss_func(self):
        loss_arr = (self.pred-self.real)**2
        return np.sum(loss_arr/self.input.shape[0])
    def gradient_decent(self, lr):
        accumulated_weight = np.zeros(w.shape)
        for i in range(self.input.shape[0]):
            accumulated_weight += (self.pred[i] - self.real[i])*self.input[i]
        accumulated_weight /= self.input.shape[0]
        self.weight -= lr*accumulated_weight
        self.predict()


# 水泥问题
$f(x) = 0.75 +1.70x_1 +1.27x_2 +0.35x_3 +0.56x_4$

In [30]:
learning_rate = 1e-6

shape = 13
x_dim = 4
x = np.array([
    [7, 26, 6, 60],
    [1, 29, 15, 52],
    [11, 56, 8, 20],
    [11, 31, 8, 47],
    [7, 52, 6, 33],
    [11, 55, 9, 22],
    [3, 71, 17, 6],
    [1, 31, 22, 44],
    [2, 54, 18, 22],
    [21, 47, 4, 26],
    [1, 40, 23, 34],
    [11, 66, 9, 12],
    [10, 68, 8, 12]
])
x = np.expand_dims(x, axis=2)
y = np.array([
    78.5,
    74.3,
    104.3,
    87.6,
    95.9,
    109.2,
    102.7,
    72.5,
    93.1,
    115.9,
    83.8,
    113.3,
    109.4
])
w = np.random.rand(x_dim+1, 1)
print(x.shape)
print(x)
print(y.shape)


(13, 4, 1)
[[[ 7]
  [26]
  [ 6]
  [60]]

 [[ 1]
  [29]
  [15]
  [52]]

 [[11]
  [56]
  [ 8]
  [20]]

 [[11]
  [31]
  [ 8]
  [47]]

 [[ 7]
  [52]
  [ 6]
  [33]]

 [[11]
  [55]
  [ 9]
  [22]]

 [[ 3]
  [71]
  [17]
  [ 6]]

 [[ 1]
  [31]
  [22]
  [44]]

 [[ 2]
  [54]
  [18]
  [22]]

 [[21]
  [47]
  [ 4]
  [26]]

 [[ 1]
  [40]
  [23]
  [34]]

 [[11]
  [66]
  [ 9]
  [12]]

 [[10]
  [68]
  [ 8]
  [12]]]
(13,)


In [31]:
lg = LinearRegression(x,y,w)
print(lg.weight)
lg.predict()
print(lg.pred)
print(lg.loss_func())
last_loss = lg.loss_func()
# lg.real.shape
print(lg.real.shape)
lg.gradient_decent(learning_rate)
print(lg.loss_func())
print(lg.weight)

(5, 1)
(5, 1)
[[0.72610681]
 [0.62745537]
 [0.49524809]
 [0.15176185]
 [0.69264712]]
[60.46414317 54.00983485 50.42904606 56.74931619 54.63912113 51.47085406
 44.50692131 50.52148697 46.69436426 55.79520233 48.20401038 49.9921118
 50.20339075]
2156.9771250871245
(13,)
2143.2333968769967
[[0.72615041]
 [0.62783059]
 [0.49756521]
 [0.15224401]
 [0.69371454]]


In [32]:
for epoch in range(100000):
# epoch = 0
# while last_loss - lg.loss_func() > 0.0001:
    last_loss = lg.loss_func()
    lg.gradient_decent(learning_rate)
    epoch += 1
    # print("epoch {}, loss:{}".format(epoch+1, lg.loss_func()))

In [33]:
print(lg.weight)

[[0.7464508 ]
 [1.70142497]
 [1.26620302]
 [0.35277013]
 [0.55978816]]


# 读物问题
$f(x) = 6.4 + 74.77x_1 + 0.91x_2$

In [20]:

shape = 18
x_dim = 2
x = np.array([
   [4, 171.2],
   [4, 174.2],
   [5,204.3],
   [4,218.7],
   [4,219.4],
   [7,240.4],
   [4,273.5],
   [5,294.8],
   [10,330.2],
   [7,333.1],
   [5,366.0],
   [6,350.9],
   [4,357.9],
   [5,359.0],
   [7,371.9],
   [9,435.3],
   [8,523.9],
   [10,604.1]
])
x = np.expand_dims(x, axis=2)
y = np.array([
    450.5,
    507.7,
    613.9,
    563.4,
    501.5,
    781.5,
    541.8,
    611.1,
    1222.1,
    793.2,
    660.8,
    792.7,
    580.8,
    612.7,
    890.8,
    1121.0,
    1094.2,
    1253.0
])
w = np.random.rand(x_dim+1, 1)
print(x.shape)
print(x)
print(y.shape)


(18, 2, 1)
[[[  4. ]
  [171.2]]

 [[  4. ]
  [174.2]]

 [[  5. ]
  [204.3]]

 [[  4. ]
  [218.7]]

 [[  4. ]
  [219.4]]

 [[  7. ]
  [240.4]]

 [[  4. ]
  [273.5]]

 [[  5. ]
  [294.8]]

 [[ 10. ]
  [330.2]]

 [[  7. ]
  [333.1]]

 [[  5. ]
  [366. ]]

 [[  6. ]
  [350.9]]

 [[  4. ]
  [357.9]]

 [[  5. ]
  [359. ]]

 [[  7. ]
  [371.9]]

 [[  9. ]
  [435.3]]

 [[  8. ]
  [523.9]]

 [[ 10. ]
  [604.1]]]
(18,)


In [21]:
lg = LinearRegression(x,y,w)
print(lg.weight)
lg.predict()
print(lg.pred)
print(lg.loss_func())
last_loss = lg.loss_func()
# lg.real.shape
print(lg.real.shape)
lg.gradient_decent(learning_rate)
print(lg.loss_func())
print(lg.weight)

(3, 1)
(3, 1)
[[0.8439082 ]
 [0.65114457]
 [0.87739445]]
[153.65841645 156.29059981 183.35131735 195.33465286 195.94882898
 216.32754616 243.41586876 262.75551513 297.07100156 297.66201174
 325.22600002 312.62848839 317.46796039 319.08423886 331.70491643
 388.63401375 465.7200175  537.38934159]
250639.34409220418
(18,)
201173.11354095972
[[0.84437448]
 [0.6543012 ]
 [1.0394736 ]]


In [22]:
# for epoch in range(100000):
while last_loss - lg.loss_func() > 0.01:
    last_loss = lg.loss_func()
    lg.gradient_decent(learning_rate)
    epoch += 1
    # print("epoch {}, loss:{}".format(epoch+1, lg.loss_func()))

In [23]:
print(lg.weight)

[[ 6.58620792]
 [74.75614455]
 [ 0.91105973]]
