In [1]:
import numpy as np
import matplotlib.pyplot as plt   

In [2]:
class LinearRegression:
    def __init__(self,x,y,w):
        x = np.concatenate((np.ones((x.shape[0], 1, 1)), x), axis=1)
        print(x[0].shape)
        print(w.shape)
        self.input = x
        self.real = y
        self.weight = w
    def predict(self):
        self.pred = np.zeros(self.input.shape[0])
        for i in range(self.input.shape[0]):
            # self.predict[i] = x[i].T*w
            # print((x[i].T.dot(w)).shape)
            # self.pred[i] = np.expand_dims(self.input[i].T.dot(self.weight), axis=0)
            self.pred[i] = np.expand_dims(self.input[i].T.dot(self.weight), axis=0)
    def loss_func(self):
        loss_arr = (self.pred-self.real)**2
        return np.sum(loss_arr)/self.input.shape[0]
    def gradient_decent(self, lr):
        self.predict()
        accumulated_weight = np.zeros(self.weight.shape, dtype=np.float64)
        for i in range(self.input.shape[0]):
            accumulated_weight += ((self.pred[i] - self.real[i])*self.input[i])
        accumulated_weight /= self.input.shape[0]
        self.weight -= lr*accumulated_weight


In [3]:
x = np.array([[1,2],[4,8]])
x = np.expand_dims(x, axis=2)
y = np.array([4,16])
w = np.random.randn(3,1)

model = LinearRegression(x,y,w)
for epoch in range(20000):
    model.gradient_decent(1e-3)
print(model.weight)
print(model.input[1])
print(model.weight.T.dot(model.input[1]))
print(model.pred)
print(model.loss_func())

(3, 1)
(3, 1)
[[8.93457282e-04]
 [8.86342838e-01]
 [1.55669638e+00]]
[[1.]
 [4.]
 [8.]]
[[15.99983586]]
[ 4.00062922 15.99983581]
2.1143796069018304e-07


# 水泥问题
$f(x) = 0.75 +1.70x_1 +1.27x_2 +0.35x_3 +0.56x_4$

In [4]:
learning_rate = 1e-5

shape = 13
x_dim = 4
x = np.array([
    [7, 26, 6, 60],
    [1, 29, 15, 52],
    [11, 56, 8, 20],
    [11, 31, 8, 47],
    [7, 52, 6, 33],
    [11, 55, 9, 22],
    [3, 71, 17, 6],
    [1, 31, 22, 44],
    [2, 54, 18, 22],
    [21, 47, 4, 26],
    [1, 40, 23, 34],
    [11, 66, 9, 12],
    [10, 68, 8, 12]
])
x = np.expand_dims(x, axis=2)
y = np.array([
    78.5,
    74.3,
    104.3,
    87.6,
    95.9,
    109.2,
    102.7,
    72.5,
    93.1,
    115.9,
    83.8,
    113.3,
    109.4
])
w = np.random.rand(x_dim+1, 1)
print(x.shape)
print(x)
print(y.shape)


(13, 4, 1)
[[[ 7]
  [26]
  [ 6]
  [60]]

 [[ 1]
  [29]
  [15]
  [52]]

 [[11]
  [56]
  [ 8]
  [20]]

 [[11]
  [31]
  [ 8]
  [47]]

 [[ 7]
  [52]
  [ 6]
  [33]]

 [[11]
  [55]
  [ 9]
  [22]]

 [[ 3]
  [71]
  [17]
  [ 6]]

 [[ 1]
  [31]
  [22]
  [44]]

 [[ 2]
  [54]
  [18]
  [22]]

 [[21]
  [47]
  [ 4]
  [26]]

 [[ 1]
  [40]
  [23]
  [34]]

 [[11]
  [66]
  [ 9]
  [12]]

 [[10]
  [68]
  [ 8]
  [12]]]
(13,)


In [5]:
lg = LinearRegression(x,y,w)
print(lg.weight)
lg.predict()
print(lg.pred)
print(lg.loss_func())
last_loss = lg.loss_func()
# lg.real.shape
print(lg.real.shape)
lg.gradient_decent(learning_rate)
print(lg.loss_func())
print(lg.weight)

(5, 1)
(5, 1)
[[0.16805726]
 [0.78383458]
 [0.58348733]
 [0.75174095]
 [0.46615745]]
[53.30546264 53.38932609 56.8026047  54.80167265 55.88988201 57.90317323
 59.52370222 56.0892278  57.03084322 59.17954547 57.4307802  59.65995933
 59.29135846]
1643.9302809238786
(13,)
1643.9302809238786
[[0.16844203]
 [0.78725886]
 [0.60351053]
 [0.75579496]
 [0.47610382]]


In [6]:
for epoch in range(100000):
# epoch = 0
# while last_loss - lg.loss_func() > 0.0001:
    last_loss = lg.loss_func()
    lg.gradient_decent(learning_rate)
    # epoch += 1
    # print("epoch {}, loss:{}".format(epoch+1, lg.loss_func()))

In [7]:
print(lg.weight)

[[0.19444711]
 [2.19083675]
 [1.15137414]
 [0.75629081]
 [0.48439029]]


# 读物问题
$f(x) = 6.4 + 74.77x_1 + 0.91x_2$

In [8]:

shape = 18
x_dim = 2
x = np.array([
   [4, 171.2],
   [4, 174.2],
   [5,204.3],
   [4,218.7],
   [4,219.4],
   [7,240.4],
   [4,273.5],
   [5,294.8],
   [10,330.2],
   [7,333.1],
   [5,366.0],
   [6,350.9],
   [4,357.9],
   [5,359.0],
   [7,371.9],
   [9,435.3],
   [8,523.9],
   [10,604.1]
])
x = np.expand_dims(x, axis=2)
y = np.array([
    450.5,
    507.7,
    613.9,
    563.4,
    501.5,
    781.5,
    541.8,
    611.1,
    1222.1,
    793.2,
    660.8,
    792.7,
    580.8,
    612.7,
    890.8,
    1121.0,
    1094.2,
    1253.0
])
w = np.random.normal(1, 0.1, (x_dim+1, 1))
print(x.shape)
print(x)
print(y.shape)


(18, 2, 1)
[[[  4. ]
  [171.2]]

 [[  4. ]
  [174.2]]

 [[  5. ]
  [204.3]]

 [[  4. ]
  [218.7]]

 [[  4. ]
  [219.4]]

 [[  7. ]
  [240.4]]

 [[  4. ]
  [273.5]]

 [[  5. ]
  [294.8]]

 [[ 10. ]
  [330.2]]

 [[  7. ]
  [333.1]]

 [[  5. ]
  [366. ]]

 [[  6. ]
  [350.9]]

 [[  4. ]
  [357.9]]

 [[  5. ]
  [359. ]]

 [[  7. ]
  [371.9]]

 [[  9. ]
  [435.3]]

 [[  8. ]
  [523.9]]

 [[ 10. ]
  [604.1]]]
(18,)


In [9]:
lg = LinearRegression(x,y,w)
epoch = 0
print(lg.weight)
lg.predict()
print(lg.pred)
print(lg.loss_func())
last_loss = lg.loss_func()
init_loss = last_loss
# lg.real.shape
print(lg.real.shape)
lg.gradient_decent(learning_rate)
print(lg.loss_func())
print(lg.weight)

(3, 1)
(3, 1)
[[0.85607322]
 [0.99823402]
 [0.92101518]]
[162.5268081  165.28985364 194.01064457 206.27502915 206.91973977
 229.25576061 256.74666101 277.36251836 314.95762582 314.63386779
 342.93879917 330.02970398 334.4803422  336.49169291 350.36925677
 410.75808722 491.36179815 567.22368362]
234589.70670292515
(18,)
234589.70670292515
[[0.86057381]
 [1.02874019]
 [2.48311868]]


In [10]:
# for epoch in range(100000):
learning_rate = 1e-5
while last_loss - lg.loss_func() > 1 or epoch < 300000:
    last_loss = lg.loss_func()
    lg.gradient_decent(learning_rate)
    epoch += 1
    # print("epoch {}, loss:{}".format(epoch+1, lg.loss_func()))

In [11]:
print("weight = ", lg.weight)
print("loss = ", last_loss)
print("init_loss =", init_loss)

weight =  [[  6.9427557 ]
 [103.58257035]
 [  0.39351693]]
loss =  1287.137792656436
init_loss = 234589.70670292515
