In [1]:
import numpy as np
import pandas as pd 
import torch
from torch import nn
from torch import optim
from torch.utils.data import DataLoader, TensorDataset

OMP: Warning #124: Ignoring invalid OS proc ID 1.


In [2]:
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
# device = 'cpu'
print(device)

cpu


In [3]:
train_data = pd.read_csv("./iris_train.data", names=['x1','x2','x3','x4','label'])
test_data = pd.read_csv("./iris_test.data", names=['x1','x2','x3','x4','label'])

train_data['label'] = pd.factorize(train_data.label)[0]
test_data['label'] = pd.factorize(test_data.label)[0]

print(train_data)
print(test_data)

     x1   x2   x3   x4  label
0   5.1  3.5  1.4  0.2      0
1   4.9  3.0  1.4  0.2      0
2   4.7  3.2  1.3  0.2      0
3   4.6  3.1  1.5  0.2      0
4   5.0  3.6  1.4  0.2      0
5   5.4  3.9  1.7  0.4      0
6   4.6  3.4  1.4  0.3      0
7   5.0  3.4  1.5  0.2      0
8   4.4  2.9  1.4  0.2      0
9   4.9  3.1  1.5  0.1      0
10  5.4  3.7  1.5  0.2      0
11  4.8  3.4  1.6  0.2      0
12  4.8  3.0  1.4  0.1      0
13  4.3  3.0  1.1  0.1      0
14  5.8  4.0  1.2  0.2      0
15  5.7  4.4  1.5  0.4      0
16  5.4  3.9  1.3  0.4      0
17  5.1  3.5  1.4  0.3      0
18  5.7  3.8  1.7  0.3      0
19  5.1  3.8  1.5  0.3      0
20  7.0  3.2  4.7  1.4      1
21  6.4  3.2  4.5  1.5      1
22  6.9  3.1  4.9  1.5      1
23  5.5  2.3  4.0  1.3      1
24  6.5  2.8  4.6  1.5      1
25  5.7  2.8  4.5  1.3      1
26  6.3  3.3  4.7  1.6      1
27  4.9  2.4  3.3  1.0      1
28  6.6  2.9  4.6  1.3      1
29  5.2  2.7  3.9  1.4      1
30  5.0  2.0  3.5  1.0      1
31  5.9  3.0  4.2  1.5      1
32  6.0  2

In [4]:
train_data = np.asarray(train_data)
test_data = np.asarray(test_data)

train_x = train_data[:,0:4]
print(train_x)
train_y = train_data[:,4]

test_x = test_data[:,0:4]
# print(test_x)
test_y = test_data[:,4]

print(test_y)

train_x = torch.tensor(train_x, dtype=torch.float).to(device)
train_y = torch.tensor(train_y, dtype=torch.long).to(device)
test_x = torch.tensor(test_x, dtype=torch.float).to(device)
test_y = torch.tensor(test_y, dtype=torch.long).to(device)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [6.5 2.8 4.6 1.5]
 [5.7 2.8 4.5 1.3]
 [6.3 3.3 4.7 1.6]
 [4.9 2.4 3.3 1. ]
 [6.6 2.9 4.6 1.3]
 [5.2 2.7 3.9 1.4]
 [5.  2.  3.5 1. ]
 [5.9 3.  4.2 1.5]
 [6.  2.2 4.  1. ]
 [6.1 2.9 4.7 1.4]
 [5.6 2.9 3.6 1.3]
 [6.7 3.1 4.4 1.4]
 [5.6 3.  4.5 1.5]
 [5.8 2.7 4.1 1. ]
 [6.2 2.2 4.5 1.5]
 [5.6 2.5 3.9 1.1]
 [6.3 3.3 6.  2.5]
 [5.8 2.7 5.1 1.9]
 [7.1 3.  5.9 2.1]
 [6.3 2.9 5.6 1.8]
 [6.5 3.  5.8 2.2]
 [7.6 3.  6.6 2.1]
 [4.9 2.5 4.5 1.7]
 [7.3 2.9 6.3 1.8]
 [6.7 2.5 5.8 1.8]
 [7.2 3.6 6.1 2.5]
 [6.5 3.2 5.1 2. ]
 [6.4 2.7 5.3 1.9]
 [6.8 3.  5.

In [5]:
batch_size = 8

train_ds = TensorDataset(train_x, train_y)
train_dl = DataLoader(train_ds, batch_size=batch_size, shuffle=True)

test_ds = TensorDataset(test_x, test_y)
test_dl = DataLoader(test_ds, batch_size=batch_size)

In [6]:
class LogisticRegression(nn.Module):
    def __init__(self) -> None:
        super().__init__()
        self.linear = nn.Sequential(
            #nn.Linear(4,32),
            #nn.ReLU(),
            #nn.Linear(32,32),
            #nn.ReLU(),
            #nn.Linear(32,3),
            nn.Linear(4,3),
        )

    def forward(self, input):
        input = self.linear(input)
        return input

In [7]:
lr_model = LogisticRegression().to(device)
print(lr_model)

loss_func = nn.CrossEntropyLoss()

lr = 1e-5

optimizer = optim.Adam(lr_model.parameters(), lr=lr)

LogisticRegression(
  (linear): Sequential(
    (0): Linear(in_features=4, out_features=3, bias=True)
  )
)


In [8]:
def accuracy(y_pred, y_true):
    y_pred = torch.argmax(y_pred, dim=1)
    acc = (y_pred == y_true).float().mean()
    return acc

In [ ]:
train_acc = []
train_loss = []
test_acc = []
test_loss = []

for epoch in range(1,30001):
    for x, y in train_dl:
        y_pred = lr_model(x)
        loss = loss_func(y_pred, y)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
    
    with torch.no_grad():
        epoch_acc = accuracy(lr_model(train_x), train_y)
        epoch_loss = loss_func(lr_model(train_x), train_y).data

        test_epoch_acc = accuracy(lr_model(test_x), test_y)
        test_epoch_loss = loss_func(lr_model(test_x), test_y).data

        if epoch % 20 == 0:
            print("epoch:%d"%epoch)
            print(f"loss:{epoch_loss.item():.3}, acc:{epoch_acc.item():.3}")
            print(f"test_loss:{test_epoch_loss.item():.3}, test_acc:{test_epoch_acc.item():.3}")
            print('-'*30)

        train_loss.append(epoch_loss.item())
        train_acc.append(epoch_acc.item())
        test_loss.append(test_epoch_loss.item())
        test_acc.append(test_epoch_acc.item())

epoch:20
loss:1.91, acc:0.661
test_loss:2.0, test_acc:0.656
------------------------------
epoch:40
loss:1.89, acc:0.661
test_loss:1.99, test_acc:0.656
------------------------------
epoch:60
loss:1.88, acc:0.661
test_loss:1.97, test_acc:0.656
------------------------------
epoch:80
loss:1.86, acc:0.661
test_loss:1.96, test_acc:0.656
------------------------------
epoch:100
loss:1.85, acc:0.661
test_loss:1.94, test_acc:0.656
------------------------------
epoch:120
loss:1.84, acc:0.661
test_loss:1.93, test_acc:0.656
------------------------------
epoch:140
loss:1.82, acc:0.661
test_loss:1.92, test_acc:0.656
------------------------------
epoch:160
loss:1.81, acc:0.661
test_loss:1.9, test_acc:0.656
------------------------------
epoch:180
loss:1.79, acc:0.661
test_loss:1.89, test_acc:0.656
------------------------------
epoch:200
loss:1.78, acc:0.661
test_loss:1.87, test_acc:0.656
------------------------------
epoch:220
loss:1.77, acc:0.661
test_loss:1.86, test_acc:0.656
--------------

epoch:1820
loss:0.867, acc:0.661
test_loss:0.903, test_acc:0.656
------------------------------
epoch:1840
loss:0.86, acc:0.661
test_loss:0.897, test_acc:0.656
------------------------------
epoch:1860
loss:0.854, acc:0.661
test_loss:0.89, test_acc:0.656
------------------------------
epoch:1880
loss:0.849, acc:0.661
test_loss:0.884, test_acc:0.656
------------------------------
epoch:1900
loss:0.843, acc:0.661
test_loss:0.877, test_acc:0.656
------------------------------
epoch:1920
loss:0.837, acc:0.661
test_loss:0.871, test_acc:0.656
------------------------------
epoch:1940
loss:0.832, acc:0.661
test_loss:0.866, test_acc:0.656
------------------------------
epoch:1960
loss:0.827, acc:0.661
test_loss:0.86, test_acc:0.656
------------------------------
epoch:1980
loss:0.822, acc:0.661
test_loss:0.855, test_acc:0.656
------------------------------
epoch:2000
loss:0.817, acc:0.661
test_loss:0.85, test_acc:0.656
------------------------------
epoch:2020
loss:0.812, acc:0.661
test_loss:0

epoch:3560
loss:0.682, acc:0.746
test_loss:0.71, test_acc:0.656
------------------------------
epoch:3580
loss:0.681, acc:0.763
test_loss:0.71, test_acc:0.688
------------------------------
epoch:3600
loss:0.681, acc:0.763
test_loss:0.709, test_acc:0.688
------------------------------
epoch:3620
loss:0.68, acc:0.78
test_loss:0.708, test_acc:0.688
------------------------------
epoch:3640
loss:0.679, acc:0.78
test_loss:0.707, test_acc:0.688
------------------------------
epoch:3660
loss:0.678, acc:0.78
test_loss:0.706, test_acc:0.688
------------------------------
epoch:3680
loss:0.677, acc:0.78
test_loss:0.706, test_acc:0.688
------------------------------
epoch:3700
loss:0.676, acc:0.78
test_loss:0.705, test_acc:0.688
------------------------------
epoch:3720
loss:0.676, acc:0.78
test_loss:0.704, test_acc:0.688
------------------------------
epoch:3740
loss:0.675, acc:0.78
test_loss:0.703, test_acc:0.688
------------------------------
epoch:3760
loss:0.674, acc:0.78
test_loss:0.703, t

epoch:5300
loss:0.617, acc:0.814
test_loss:0.651, test_acc:0.719
------------------------------
epoch:5320
loss:0.616, acc:0.814
test_loss:0.65, test_acc:0.719
------------------------------
epoch:5340
loss:0.615, acc:0.814
test_loss:0.649, test_acc:0.719
------------------------------
epoch:5360
loss:0.615, acc:0.814
test_loss:0.649, test_acc:0.719
------------------------------
epoch:5380
loss:0.614, acc:0.814
test_loss:0.648, test_acc:0.719
------------------------------
epoch:5400
loss:0.613, acc:0.814
test_loss:0.648, test_acc:0.719
------------------------------
epoch:5420
loss:0.613, acc:0.814
test_loss:0.647, test_acc:0.719
------------------------------
epoch:5440
loss:0.612, acc:0.814
test_loss:0.646, test_acc:0.719
------------------------------
epoch:5460
loss:0.611, acc:0.814
test_loss:0.646, test_acc:0.719
------------------------------
epoch:5480
loss:0.611, acc:0.814
test_loss:0.645, test_acc:0.719
------------------------------
epoch:5500
loss:0.61, acc:0.814
test_loss

epoch:7040
loss:0.565, acc:0.847
test_loss:0.604, test_acc:0.781
------------------------------
epoch:7060
loss:0.565, acc:0.847
test_loss:0.604, test_acc:0.781
------------------------------
epoch:7080
loss:0.564, acc:0.847
test_loss:0.603, test_acc:0.781
------------------------------
epoch:7100
loss:0.564, acc:0.847
test_loss:0.603, test_acc:0.781
------------------------------
epoch:7120
loss:0.563, acc:0.847
test_loss:0.602, test_acc:0.781
------------------------------
epoch:7140
loss:0.563, acc:0.847
test_loss:0.602, test_acc:0.812
------------------------------
epoch:7160
loss:0.562, acc:0.847
test_loss:0.601, test_acc:0.812
------------------------------
epoch:7180
loss:0.562, acc:0.847
test_loss:0.601, test_acc:0.812
------------------------------
epoch:7200
loss:0.561, acc:0.847
test_loss:0.6, test_acc:0.812
------------------------------
epoch:7220
loss:0.561, acc:0.847
test_loss:0.6, test_acc:0.812
------------------------------
epoch:7240
loss:0.56, acc:0.847
test_loss:0.

epoch:8780
loss:0.525, acc:0.898
test_loss:0.567, test_acc:0.906
------------------------------
epoch:8800
loss:0.525, acc:0.898
test_loss:0.567, test_acc:0.906
------------------------------
epoch:8820
loss:0.524, acc:0.898
test_loss:0.567, test_acc:0.906
------------------------------
epoch:8840
loss:0.524, acc:0.898
test_loss:0.566, test_acc:0.906
------------------------------
epoch:8860
loss:0.523, acc:0.898
test_loss:0.566, test_acc:0.906
------------------------------
epoch:8880
loss:0.523, acc:0.898
test_loss:0.566, test_acc:0.906
------------------------------
epoch:8900
loss:0.523, acc:0.898
test_loss:0.565, test_acc:0.906
------------------------------
epoch:8920
loss:0.522, acc:0.898
test_loss:0.565, test_acc:0.906
------------------------------
epoch:8940
loss:0.522, acc:0.898
test_loss:0.565, test_acc:0.906
------------------------------
epoch:8960
loss:0.521, acc:0.898
test_loss:0.564, test_acc:0.906
------------------------------
epoch:8980
loss:0.521, acc:0.898
test_lo

epoch:10520
loss:0.492, acc:0.915
test_loss:0.537, test_acc:0.906
------------------------------
epoch:10540
loss:0.492, acc:0.915
test_loss:0.537, test_acc:0.906
------------------------------
epoch:10560
loss:0.491, acc:0.915
test_loss:0.537, test_acc:0.906
------------------------------
epoch:10580
loss:0.491, acc:0.915
test_loss:0.537, test_acc:0.906
------------------------------
epoch:10600
loss:0.491, acc:0.915
test_loss:0.536, test_acc:0.906
------------------------------
epoch:10620
loss:0.49, acc:0.915
test_loss:0.536, test_acc:0.906
------------------------------
epoch:10640
loss:0.49, acc:0.915
test_loss:0.536, test_acc:0.906
------------------------------
epoch:10660
loss:0.49, acc:0.915
test_loss:0.535, test_acc:0.906
------------------------------
epoch:10680
loss:0.489, acc:0.915
test_loss:0.535, test_acc:0.906
------------------------------
epoch:10700
loss:0.489, acc:0.915
test_loss:0.535, test_acc:0.906
------------------------------
epoch:10720
loss:0.489, acc:0.915

epoch:12260
loss:0.465, acc:0.915
test_loss:0.513, test_acc:0.906
------------------------------
epoch:12280
loss:0.464, acc:0.915
test_loss:0.512, test_acc:0.906
------------------------------
epoch:12300
loss:0.464, acc:0.915
test_loss:0.512, test_acc:0.906
------------------------------
epoch:12320
loss:0.464, acc:0.915
test_loss:0.512, test_acc:0.906
------------------------------
epoch:12340
loss:0.463, acc:0.915
test_loss:0.512, test_acc:0.906
------------------------------
epoch:12360
loss:0.463, acc:0.915
test_loss:0.511, test_acc:0.906
------------------------------
epoch:12380
loss:0.463, acc:0.915
test_loss:0.511, test_acc:0.906
------------------------------
epoch:12400
loss:0.463, acc:0.915
test_loss:0.511, test_acc:0.906
------------------------------
epoch:12420
loss:0.462, acc:0.915
test_loss:0.511, test_acc:0.906
------------------------------
epoch:12440
loss:0.462, acc:0.915
test_loss:0.51, test_acc:0.906
------------------------------
epoch:12460
loss:0.462, acc:0.9

epoch:14000
loss:0.441, acc:0.932
test_loss:0.492, test_acc:0.906
------------------------------
epoch:14020
loss:0.441, acc:0.932
test_loss:0.492, test_acc:0.906
------------------------------
epoch:14040
loss:0.441, acc:0.932
test_loss:0.491, test_acc:0.906
------------------------------
epoch:14060
loss:0.441, acc:0.932
test_loss:0.491, test_acc:0.906
------------------------------
epoch:14080
loss:0.44, acc:0.932
test_loss:0.491, test_acc:0.906
------------------------------
epoch:14100
loss:0.44, acc:0.932
test_loss:0.491, test_acc:0.906
------------------------------
epoch:14120
loss:0.44, acc:0.932
test_loss:0.49, test_acc:0.906
------------------------------
epoch:14140
loss:0.44, acc:0.932
test_loss:0.49, test_acc:0.906
------------------------------
epoch:14160
loss:0.439, acc:0.932
test_loss:0.49, test_acc:0.906
------------------------------
epoch:14180
loss:0.439, acc:0.932
test_loss:0.49, test_acc:0.906
------------------------------
epoch:14200
loss:0.439, acc:0.932
test

epoch:15740
loss:0.421, acc:0.949
test_loss:0.474, test_acc:0.938
------------------------------
epoch:15760
loss:0.421, acc:0.949
test_loss:0.474, test_acc:0.938
------------------------------
epoch:15780
loss:0.421, acc:0.949
test_loss:0.473, test_acc:0.938
------------------------------
epoch:15800
loss:0.42, acc:0.949
test_loss:0.473, test_acc:0.938
------------------------------
epoch:15820
loss:0.42, acc:0.949
test_loss:0.473, test_acc:0.938
------------------------------
epoch:15840
loss:0.42, acc:0.949
test_loss:0.473, test_acc:0.938
------------------------------
epoch:15860
loss:0.42, acc:0.949
test_loss:0.473, test_acc:0.938
------------------------------
epoch:15880
loss:0.42, acc:0.949
test_loss:0.472, test_acc:0.938
------------------------------
epoch:15900
loss:0.419, acc:0.949
test_loss:0.472, test_acc:0.938
------------------------------
epoch:15920
loss:0.419, acc:0.949
test_loss:0.472, test_acc:0.938
------------------------------
epoch:15940
loss:0.419, acc:0.949
t

epoch:17480
loss:0.403, acc:0.966
test_loss:0.458, test_acc:0.938
------------------------------
epoch:17500
loss:0.403, acc:0.966
test_loss:0.458, test_acc:0.938
------------------------------
epoch:17520
loss:0.403, acc:0.966
test_loss:0.458, test_acc:0.938
------------------------------
epoch:17540
loss:0.403, acc:0.966
test_loss:0.457, test_acc:0.938
------------------------------
epoch:17560
loss:0.402, acc:0.966
test_loss:0.457, test_acc:0.938
------------------------------
epoch:17580
loss:0.402, acc:0.966
test_loss:0.457, test_acc:0.938
------------------------------
epoch:17600
loss:0.402, acc:0.966
test_loss:0.457, test_acc:0.938
------------------------------
epoch:17620
loss:0.402, acc:0.966
test_loss:0.457, test_acc:0.938
------------------------------
epoch:17640
loss:0.402, acc:0.966
test_loss:0.457, test_acc:0.938
------------------------------
epoch:17660
loss:0.401, acc:0.966
test_loss:0.456, test_acc:0.938
------------------------------
epoch:17680
loss:0.401, acc:0.

epoch:19220
loss:0.387, acc:0.966
test_loss:0.444, test_acc:0.938
------------------------------
epoch:19240
loss:0.387, acc:0.966
test_loss:0.444, test_acc:0.938
------------------------------
epoch:19260
loss:0.387, acc:0.966
test_loss:0.443, test_acc:0.938
------------------------------
epoch:19280
loss:0.386, acc:0.966
test_loss:0.443, test_acc:0.938
------------------------------
epoch:19300
loss:0.386, acc:0.966
test_loss:0.443, test_acc:0.938
------------------------------
epoch:19320
loss:0.386, acc:0.966
test_loss:0.443, test_acc:0.938
------------------------------
epoch:19340
loss:0.386, acc:0.966
test_loss:0.443, test_acc:0.938
------------------------------
epoch:19360
loss:0.386, acc:0.966
test_loss:0.443, test_acc:0.938
------------------------------
epoch:19380
loss:0.386, acc:0.966
test_loss:0.442, test_acc:0.938
------------------------------
epoch:19400
loss:0.385, acc:0.966
test_loss:0.442, test_acc:0.938
------------------------------
epoch:19420
loss:0.385, acc:0.

epoch:20960
loss:0.372, acc:0.983
test_loss:0.431, test_acc:0.938
------------------------------
epoch:20980
loss:0.372, acc:0.983
test_loss:0.431, test_acc:0.938
------------------------------
epoch:21000
loss:0.372, acc:0.983
test_loss:0.431, test_acc:0.938
------------------------------
epoch:21020
loss:0.372, acc:0.983
test_loss:0.43, test_acc:0.938
------------------------------
epoch:21040
loss:0.372, acc:0.983
test_loss:0.43, test_acc:0.938
------------------------------
epoch:21060
loss:0.372, acc:0.983
test_loss:0.43, test_acc:0.938
------------------------------
epoch:21080
loss:0.371, acc:0.983
test_loss:0.43, test_acc:0.938
------------------------------
epoch:21100
loss:0.371, acc:0.983
test_loss:0.43, test_acc:0.938
------------------------------
epoch:21120
loss:0.371, acc:0.983
test_loss:0.43, test_acc:0.938
------------------------------
epoch:21140
loss:0.371, acc:0.983
test_loss:0.43, test_acc:0.938
------------------------------
epoch:21160
loss:0.371, acc:0.983
tes

epoch:22700
loss:0.359, acc:0.983
test_loss:0.419, test_acc:0.938
------------------------------
epoch:22720
loss:0.359, acc:0.983
test_loss:0.419, test_acc:0.938
------------------------------
epoch:22740
loss:0.359, acc:0.983
test_loss:0.419, test_acc:0.938
------------------------------
epoch:22760
loss:0.358, acc:0.983
test_loss:0.419, test_acc:0.938
------------------------------
epoch:22780
loss:0.358, acc:0.983
test_loss:0.419, test_acc:0.938
------------------------------
epoch:22800
loss:0.358, acc:0.983
test_loss:0.419, test_acc:0.938
------------------------------
epoch:22820
loss:0.358, acc:0.983
test_loss:0.418, test_acc:0.938
------------------------------
epoch:22840
loss:0.358, acc:0.983
test_loss:0.418, test_acc:0.938
------------------------------
epoch:22860
loss:0.358, acc:0.983
test_loss:0.418, test_acc:0.938
------------------------------
epoch:22880
loss:0.357, acc:0.983
test_loss:0.418, test_acc:0.938
------------------------------
epoch:22900
loss:0.357, acc:0.

In [ ]:
import matplotlib.pyplot as plt

plt.figure(dpi=150)
plt.plot(range(epoch), train_loss, label='train_loss')
plt.plot(range(epoch), test_loss, label='test_loss')
plt.legend()

In [ ]:
plt.figure(dpi=150)
plt.plot(range(epoch), train_acc, label='train_acc')
plt.plot(range(epoch), test_acc, label='test_acc')
plt.legend()